### ISSUE TITLE
Issues with loading Quick Carpet with Fabric Profile on MC 1.14.4

### ISSUE THREAD

**Issue by dyashayev** [DeadlyMC/QuickCarpet114#43]
I am attempting to use the carpet mod's void generation with the random item skyblock datapack, but it seems that I am getting this problem for my single player profile that is created via the fabric installer. I am able to load the profile when my mods folder is empty :

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 9/28/19 9:04 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
at net.minecraft.class_310.method_1503(class_310.java:445)
at net.minecraft.class_310.method_1514(class_310.java:394)
at net.minecraft.client.main.Main.main(Main.java:155)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Suppressed: java.lang.IllegalStateException: Error initializing SkyBlock
at skyblock.SkyBlockLoader.onInitialize(SkyBlockLoader.java:19)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$1502/485302201.accept(Unknown Source)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils$$Lambda$1503/837007490.accept(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
... 11 more
Caused by: java.lang.NullPointerException
at quickcarpet.utils.Translations.loadModuleTranslations(Translations.java:35)
at quickcarpet.utils.Translations.loadModuleTranslations(Translations.java:53)
at quickcarpet.QuickCarpet.registerModule(QuickCarpet.java:128)
at skyblock.SkyBlockLoader.onInitialize(SkyBlockLoader.java:13)
... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Client thread
Stacktrace:
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
at net.minecraft.class_310.method_1503(class_310.java:445)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.class_310.method_1514(class_310.java:394)
at net.minecraft.client.main.Main.main(Main.java:155)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
Minecraft Version: 1.14.4
Minecraft Version ID: 1.14.4
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 931066768 bytes (887 MB) / 1509949440 bytes (1440 MB) up to 2147483648 bytes (2048 MB)
CPUs: 4
JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
Launched Version: fabric-loader-0.6.2+build.166-1.14.4
LWJGL: 3.2.2 build 10
OpenGL: NO CONTEXT
GL Caps:
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fabric'
Type: Client (map_client.txt)
Resource Packs:
Current Language: ERROR NullPointerException: null
CPU:

**Comment by skyrising** [comment]
Fixed in https://github.com/skyrising/skyblock/commit/3c26a841a940a7a3ee4c840fddd03aa2c34e5301 (Release [2.0.0-dev.20191127.134942](https://github.com/skyrising/skyblock/releases/tag/2.0.0-dev.20191127.134942))
