### ISSUE TITLE
Error when loading latest version in MultiMC

### ISSUE THREAD

**Issue by florisdegraaff** [DeadlyMC/QuickCarpet114#49]
I am loading this mod in MultiMC, MC version `1.14.4` and Fabric version `0.7.2+build.174`, but I get this error when loading it:
```[13:38:58] [main/FATAL]: Mixin apply failed quickcarpet.mixins.json:DispenserBehaviourMixin -> net.minecraft.class_2357: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Mixin quickcarpet.mixins.json:DispenserBehaviourMixin contains non-private static method onRegisterDefaults(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [ -> MAIN Applicator Phase -> quickcarpet.mixins.json:DispenserBehaviourMixin -> Apply Methods -> (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V:handler$zfj000$onRegisterDefaults]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Mixin quickcarpet.mixins.json:DispenserBehaviourMixin contains non-private static method onRegisterDefaults(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [ -> MAIN Applicator Phase -> quickcarpet.mixins.json:DispenserBehaviourMixin -> Apply Methods -> (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V:handler$zfj000$onRegisterDefaults]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.checkMethodVisibility(MixinApplicatorStandard.java:1071) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:526) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:509) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:381) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.7.2+build.174.jar:0.8+build.16+unknown-b16.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174) ~[fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) ~[fabric-loader-0.7.2+build.174.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) ~[fabric-loader-0.7.2+build.174.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.class_2315.method_10008(class_2315.java:43) ~[intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_156.method_654(class_156.java:276) ~[intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_2315.<clinit>(class_2315.java:43) ~[intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:91) ~[intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_2378.method_10237(class_2378.java:77) ~[intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_2378.method_10238(class_2378.java:117) ~[intermediary-minecraft-1.14.4-client.jar:?]
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(Unknown Source) [?:1.8.0_201]
	at net.minecraft.class_2378.<clinit>(class_2378.java:116) [intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:38) [intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:383) [intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) [intermediary-minecraft-1.14.4-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.2+build.174.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [quickcarpet.mixins.json:DispenserBehaviourMixin] from phase [DEFAULT] in config [quickcarpet.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:612)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:564)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:349)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_2315.method_10008(class_2315.java:43)
	at net.minecraft.class_156.method_654(class_156.java:276)
	at net.minecraft.class_2315.<clinit>(class_2315.java:43)
	at net.minecraft.class_2246.<clinit>(class_2246.java:91)
	at net.minecraft.class_2378.method_10237(class_2378.java:77)
	at net.minecraft.class_2378.method_10238(class_2378.java:117)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(Unknown Source)
	at net.minecraft.class_2378.<clinit>(class_2378.java:116)
	at net.minecraft.class_2966.method_12851(class_2966.java:38)
	at net.minecraft.class_310.<init>(class_310.java:383)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Mixin quickcarpet.mixins.json:DispenserBehaviourMixin contains non-private static method onRegisterDefaults(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [ -> MAIN Applicator Phase -> quickcarpet.mixins.json:DispenserBehaviourMixin -> Apply Methods -> (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V:handler$zfj000$onRegisterDefaults]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.checkMethodVisibility(MixinApplicatorStandard.java:1071)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:526)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:509)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	... 37 more
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:195)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:357)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_2315.method_10008(class_2315.java:43)
	at net.minecraft.class_156.method_654(class_156.java:276)
	at net.minecraft.class_2315.<clinit>(class_2315.java:43)
	at net.minecraft.class_2246.<clinit>(class_2246.java:91)
	at net.minecraft.class_2378.method_10237(class_2378.java:77)
	at net.minecraft.class_2378.method_10238(class_2378.java:117)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(Unknown Source)
	at net.minecraft.class_2378.<clinit>(class_2378.java:116)
	at net.minecraft.class_2966.method_12851(class_2966.java:38)
	at net.minecraft.class_310.<init>(class_310.java:383)
	at net.minecraft.client.main.Main.main(Main.java:155)
	... 15 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [quickcarpet.mixins.json:DispenserBehaviourMixin] from phase [DEFAULT] in config [quickcarpet.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:612)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:564)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:349)
	... 37 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Mixin quickcarpet.mixins.json:DispenserBehaviourMixin contains non-private static method onRegisterDefaults(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [ -> MAIN Applicator Phase -> quickcarpet.mixins.json:DispenserBehaviourMixin -> Apply Methods -> (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V:handler$zfj000$onRegisterDefaults]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.checkMethodVisibility(MixinApplicatorStandard.java:1071)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:526)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:509)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	... 37 more```

I have tried to make a new instance with only Fabric, this mod and the Fabric API mod (latest version), but without success

**Comment by skyrising** [comment]
See #50 
Technically this issue is duplicated by it but there's already a conversation going on in the other issue.
