### ISSUE TITLE
my minecraft often crashes

### ISSUE THREAD

**Issue by zhou77521** [DeadlyMC/QuickCarpet114#50]
when i try to star my minecraft launcher, it  crashes,i don't know what caused this.i just loaded two mods(quickcarpet114 and skyblock).this is my log.please help me.

`12:56:08.632
Preparing to launch minecraft client for fabric-loader-0.7.3+build.176-1.14.4
12:56:10.690
Checking installations.
12:56:10.691
Minecraft client fabric-loader-0.7.3+build.176-1.14.4 is ready to start.
12:56:10.692
Starting!
12:56:10.902
Using default game log configuration client-1.12.xml (outputs XML)
12:56:12.181
Loading for game Minecraft 1.14.4
12:56:15.415
Mod ID bbor uses outdated schema version: 0 < 1
12:56:15.419
[FabricLoader] Loading 33 mods: minecraft@1.14.4, fabric-renderer-api-v1@0.1.1+933c24c242, fabric-networking-blockentity-v0@0.2.1+28f8190f42, fabric-keybindings-v0@0.1.1+933c24c242, fabricloader@0.7.3+build.176, bbor@1.0.14-1.14.4, fabric-renderer-indigo@0.1.14+28f8190f42, fabric-containers-v0@0.1.3+28f8190f42, fabric-dimensions-v1@0.1.1+28f8190f42, fabric-biomes-v1@0.1.1+28f8190f42, fabric-events-interaction-v0@0.1.2+28f8190f42, fabric-crash-report-info-v1@0.1.2+28f8190f42, quickcarpet@2.0.0-dev.20190830.115222, fabric-api-base@0.1.2+28f8190f42, fabric-rendering-v0@0.1.2+28f8190f42, fabric-rendering-data-attachment-v1@0.1.2+28f8190f42, fabric-resource-loader-v0@0.1.4+28f8190f42, fabric-textures-v0@0.1.4+933c24c242, fabric-content-registries-v0@0.1.2+28f8190f42, fabric-tag-extensions-v0@0.1.3+d423005742, fabric-rendering-fluids-v1@0.1.3+28f8190f42, fabric-registry-sync-v0@0.2.3+28f8190f42, fabric-commands-v0@0.1.2+28f8190f42, fabric-mining-levels-v0@0.1.1+28f8190f42, fabric-loot-tables-v1@0.1.1+28f8190f42, fabric-events-lifecycle-v0@0.1.1+28f8190f42, fabric@0.4.2+build.246-1.14, skyblock@2.0.0-dev.20190721.211527, fabric-particles-v1@0.1.1+933c24c242, fabric-models-v0@0.1.0+933c24c242, fabric-item-groups-v0@0.1.1+28f8190f42, fabric-networking-v0@0.1.4+28f8190f42, fabric-object-builders-v0@0.1.2+28f8190f42
12:56:15.458
SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/%e5%91%a8%e8%b4%ba/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.17/sponge-mixin-0.8+build.17.jar Service=Knot/Fabric Env=CLIENT
12:56:17.081
Setting user: _DeacleCarbone_I
12:56:17.855
Mixin apply failed quickcarpet.mixins.json:DispenserBehaviourMixin -> net.minecraft.class_2357: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Mixin quickcarpet.mixins.json:DispenserBehaviourMixin contains non-private static method onRegisterDefaults(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [ -> MAIN Applicator Phase -> quickcarpet.mixins.json:DispenserBehaviourMixin -> Apply Methods -> (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V:handler$zfj000$onRegisterDefaults]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Mixin quickcarpet.mixins.json:DispenserBehaviourMixin contains non-private static method onRegisterDefaults(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [ -> MAIN Applicator Phase -> quickcarpet.mixins.json:DispenserBehaviourMixin -> Apply Methods -> (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V:handler$zfj000$onRegisterDefaults]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.checkMethodVisibility(MixinApplicatorStandard.java:1071)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:526)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:509)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_2315.method_10008(class_2315.java:43)
	at net.minecraft.class_2315$$Lambda$189/540811471.accept(Unknown Source)
	at net.minecraft.class_156.method_654(class_156.java:276)
	at net.minecraft.class_2315.<clinit>(class_2315.java:43)
	at net.minecraft.class_2246.<clinit>(class_2246.java:91)
	at net.minecraft.class_2378.method_10237(class_2378.java:77)
	at net.minecraft.class_2378$$Lambda$103/609887969.get(Unknown Source)
	at net.minecraft.class_2378.method_10238(class_2378.java:117)
	at net.minecraft.class_2378$$Lambda$137/936906727.accept(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
	at net.minecraft.class_2378.<clinit>(class_2378.java:116)
	at net.minecraft.class_2966.method_12851(class_2966.java:38)
	at net.minecraft.class_310.<init>(class_310.java:383)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
12:56:18.162

org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [quickcarpet.mixins.json:DispenserBehaviourMixin] from phase [DEFAULT] in config [quickcarpet.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:612)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:564)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:349)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_2315.method_10008(class_2315.java:43)
	at net.minecraft.class_2315$$Lambda$189/540811471.accept(Unknown Source)
	at net.minecraft.class_156.method_654(class_156.java:276)
	at net.minecraft.class_2315.<clinit>(class_2315.java:43)
	at net.minecraft.class_2246.<clinit>(class_2246.java:91)
	at net.minecraft.class_2378.method_10237(class_2378.java:77)
	at net.minecraft.class_2378$$Lambda$103/609887969.get(Unknown Source)
	at net.minecraft.class_2378.method_10238(class_2378.java:117)
	at net.minecraft.class_2378$$Lambda$137/936906727.accept(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
	at net.minecraft.class_2378.<clinit>(class_2378.java:116)
	at net.minecraft.class_2966.method_12851(class_2966.java:38)
	at net.minecraft.class_310.<init>(class_310.java:383)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Mixin quickcarpet.mixins.json:DispenserBehaviourMixin contains non-private static method onRegisterDefaults(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [ -> MAIN Applicator Phase -> quickcarpet.mixins.json:DispenserBehaviourMixin -> Apply Methods -> (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V:handler$zfj000$onRegisterDefaults]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.checkMethodVisibility(MixinApplicatorStandard.java:1071)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:526)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:509)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	... 32 more
Exception in thread "Client thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:195)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:357)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_2315.method_10008(class_2315.java:43)
	at net.minecraft.class_2315$$Lambda$189/540811471.accept(Unknown Source)
	at net.minecraft.class_156.method_654(class_156.java:276)
	at net.minecraft.class_2315.<clinit>(class_2315.java:43)
	at net.minecraft.class_2246.<clinit>(class_2246.java:91)
	at net.minecraft.class_2378.method_10237(class_2378.java:77)
	at net.minecraft.class_2378$$Lambda$103/609887969.get(Unknown Source)
	at net.minecraft.class_2378.method_10238(class_2378.java:117)
	at net.minecraft.class_2378$$Lambda$137/936906727.accept(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
	at net.minecraft.class_2378.<clinit>(class_2378.java:116)
	at net.minecraft.class_2966.method_12851(class_2966.java:38)
	at net.minecraft.class_310.<init>(class_310.java:383)
	at net.minecraft.client.main.Main.main(Main.java:155)
	... 7 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [quickcarpet.mixins.json:DispenserBehaviourMixin] from phase [DEFAULT] in config [quickcarpet.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:612)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:564)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:349)
	... 32 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Mixin quickcarpet.mixins.json:DispenserBehaviourMixin contains non-private static method onRegisterDefaults(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [ -> MAIN Applicator Phase -> quickcarpet.mixins.json:DispenserBehaviourMixin -> Apply Methods -> (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V:handler$zfj000$onRegisterDefaults]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.checkMethodVisibility(MixinApplicatorStandard.java:1071)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:526)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:509)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	... 32 more`

**Comment by DeadlyMC** [comment]
Looks like a newer version of the 1.14 build is not released on github.. You can get the latest release from #mods on the scicraft discord
Alternatively, u can also use java 8 to fix this issue...u probably r using a newer version of java

**Comment by zhou77521** [comment]
thinks for your hlep
yes my minecraft version is 1.14.4,and i tried many version of the mod(skyblock) ,but none one of them worked,i guess the version is not compatible,but i can't solve it.
Finally . i'd like to ask if the skyblock will be updated later,
(My English is not very good,There may be have some mistake in the sentences,I hope you can forgive me)

**Comment by DeadlyMC** [comment]
Skyblock will be updated to what?

**Comment by zhou77521** [comment]
QuickCarpet with skyblock for minecraft v1.14.4,
because I don't see an integration package for Minecraft 1.14.4 on your homepage,So,i think if you will be update this mod(quickcarpet with skyblock)
As far as i know,many people want to play this mod , but they are not very clear how to use this mod,and i also asked many people how to use this mod ,but no one can solve my problem 
I imaged if we have the integration package(quickcarpet with skyblock) for Minecraft v1.14.4 everything will be convenient。
Thank you very much for taking the time to reply my message.
Happy new year!

**Comment by skyrising** [comment]
I'd recommend updating to 1.15.1.
I'll try to backport 2.0.2 to 1.14.4 but I can't promise anything.

**Comment by zhou77521** [comment]
Thank you so much!
I never thought that the author would be so enthusiastic to help me solve the problem, I am so happy,and I will always pay attention to you.
creator!
