### ISSUE TITLE
The game cannot run

### ISSUE THREAD

**Issue by zhou77521** [DeadlyMC/QuickCarpet114#51]
When my game is  loaded to 100%. It will be forced to quit, I don't know why!
 This is my crash log.

`---- Minecraft Crash Report ----
// You're mean.

Time: 1/7/20 2:39 PM
Description: Exception ticking world

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:357)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_3215.method_20801(class_3215.java:362)
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661)
	at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105)
	at net.minecraft.class_3215.method_14161(class_3215.java:327)
	at net.minecraft.class_3215.method_12127(class_3215.java:296)
	at net.minecraft.class_3218.method_18765(class_3218.java:310)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:763)
	at net.minecraft.class_1132.method_3748(class_1132.java:128)
	at net.minecraft.server.MinecraftServer.handler$zzp000$modifiedRunLoop(MinecraftServer.java:2239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:610)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_1948::method_8663(Lnet/minecraft/class_1311;Lnet/minecraft/class_1937;Lnet/minecraft/class_2818;Lnet/minecraft/class_2338;)V has incompatible changes at opcode 281 in callback net/minecraft/class_1948::onAttempt.
Expected: [Lnet/minecraft/class_2794;, I, Lnet/minecraft/class_2338;, I, I, I, Lnet/minecraft/class_2680;, Lnet/minecraft/class_2338$class_2339;, I, I, I, I, Lnet/minecraft/class_1959$class_1964;]
   Found: [Lnet/minecraft/class_2794;, I, Lnet/minecraft/class_2338;, I, I, I, Lnet/minecraft/class_2338$class_2339;, I, I, I, I, Lnet/minecraft/class_1959$class_1964;, Lnet/minecraft/class_1315;]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:487)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:437)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:377)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1273)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:357)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_3215.method_20801(class_3215.java:362)
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661)
	at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105)
	at net.minecraft.class_3215.method_14161(class_3215.java:327)
	at net.minecraft.class_3215.method_12127(class_3215.java:296)
	at net.minecraft.class_3218.method_18765(class_3218.java:310)

-- Affected level --
Details:
	All players: 1 total; [class_3222['_DeacleCarbone_I'/27, l='New World', x=-247.50, y=65.00, z=232.50]]
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level name: New World
	Level seed: -2138059213954130314
	Level generator: ID 15 - skyblock, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-248,64,232), Chunk: (at 8,4,8 in -16,14; contains blocks -256,0,224 to -241,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 58 game time, 58 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 43501 (now: false), thunder time: 42007 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:763)
	at net.minecraft.class_1132.method_3748(class_1132.java:128)
	at net.minecraft.server.MinecraftServer.handler$zzp000$modifiedRunLoop(MinecraftServer.java:2239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:610)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.14.3 Pre-Release 2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1005370832 bytes (958 MB) / 2105540608 bytes (2008 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms409m -Xmx4096m
	Player Count: 1 / 8; [class_3222['_DeacleCarbone_I'/27, l='New World', x=-247.50, y=65.00, z=232.50]]
	Data Packs: vanilla, fabric/quickcarpet, fabric/minecraft
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'`

**Comment by skyrising** [comment]
This was fixed at some point. The latest version should work.
