### ISSUE TITLE
1.15.2添加quickCarpet2.1.0导致游戏崩溃

### ISSUE THREAD

**Issue by Stele1024** [DeadlyMC/QuickCarpet114#57]
我在客户端的mod加入quickCarpet会在启动游戏时导致游戏崩溃，在服务端添加quickcarpet到mods文件夹也会导致minecraft  server 启动失败。

我的Minecraft 版本：1.15.2
fabric版本： 0.5.2.40
服务端报错日志：
```
[02:17:11] [main/INFO]: Loading for game Minecraft 1.15.2
[02:17:14] [main/WARN]: Mod ID bbor uses outdated schema version: 0 < 1
[02:17:14] [main/WARN]: Mod `quickcarpet` (2.1.0) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[02:17:14] [main/WARN]: Mod `lightoverlay` (4.3) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[02:17:14] [main/INFO]: [FabricLoader] Loading 48 mods: fabric-renderer-api-v1@0.2.10+f08b61330c, minecraft@1.15.2, fabric-networking-blockentity-v0@0.2.3+e08a73050c, fabric-keybindings-v0@0.1.1+dfdb52d60c, modmenu@1.10.2+build.32, cloth-basic-math@0.4.1, fabricloader@0.8.4+build.198, bbor@1.0.14-1.15.1, fabric-renderer-indigo@0.2.23+9290e2ed0c, fabric-containers-v0@0.1.3+b7f9825d0c, fabric-dimensions-v1@0.3.0+2ad156310c, fabric-biomes-v1@0.1.5+3b05f68e0c, fabric-crash-report-info-v1@0.1.2+b7f9825d0c, fabric-events-interaction-v0@0.3.0+fac69e320c, quickcarpet@2.1.0, fabric-api-base@0.1.2+b7f9825d0c, fabric-rendering-v0@1.1.0+534104900c, fabric-rendering-v1@0.1.0+534104900c, cloth-config2@2.11.1, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d0c, fabric-resource-loader-v0@0.1.10+06c939b30c, tweakeroo@0.10.0-dev.20200303.202420, fabric-textures-v0@1.0.4+821cdba70c, malilib@0.10.0-dev.20+arne.6, fabric-content-registries-v0@0.1.3+b7f9825d0c, fabric-tag-extensions-v0@0.1.3+abd915800c, fabric-rendering-fluids-v1@0.1.6+12515ed90c, appleskin@1.0.8, fabric-commands-v0@0.1.2+b7f9825d0c, fabric-registry-sync-v0@0.2.6+f3d8141b0c, waila@1.9.21, fabric-blockrenderlayer-v1@1.1.4+c6a8ea890c, lightoverlay@4.3, itemscroller@0.15.0-dev.20200212.183513, fabric-mining-levels-v0@0.1.1+b7f9825d0c, fabric-renderer-registries-v1@2.0.1+5a0f9a600c, minihud@0.19.0-dev.20200303.193734, voxelmap@1.9.16, fabric-loot-tables-v1@0.1.5+e08a73050c, fabric-events-lifecycle-v0@0.1.2+b7f9825d0c, fabric@0.5.1+build.294-1.15, carpet@1.3.9, fabric-particles-v1@0.1.1+dfdb52d60c, fabric-item-groups-v0@0.1.6+ec40b2e10c, fabric-models-v0@0.1.0+dfdb52d60c, fabric-networking-v0@0.1.7+12515ed90c, fabric-object-builders-v0@0.1.3+e4c9a9c30c, cloth@1.2.0
[02:17:14] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Game/Minecraft/%e7%a9%ba%e5%b2%9b1.15.2/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[02:17:16] [main/WARN]: @Redirect conflict. Skipping carpet.mixins.json:MinecraftServer_tickspeedMixin->@Redirect::cancelRunLoop(Lnet/minecraft/server/MinecraftServer;)Z with priority 1000, already redirected by quickcarpet.mixins.json:tickSpeed.MinecraftServerMixin->@Redirect::cancelRunLoop(Lnet/minecraft/server/MinecraftServer;)Z with priority 1000
org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector cancelRunLoop(Lnet/minecraft/server/MinecraftServer;)Z in carpet.mixins.json:MinecraftServer_tickspeedMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-carpet-refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:190)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:51)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:107)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:63)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
        ... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:190)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
        ... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector cancelRunLoop(Lnet/minecraft/server/MinecraftServer;)Z in carpet.mixins.json:MinecraftServer_tickspeedMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-carpet-refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
```

**Comment by skyrising** [comment]
You're trying to use fabric-carpet and quickcarpet at the same time, which is not possible.
