### ISSUE TITLE
Server Fails to Launch

### ISSUE THREAD

**Issue by Huntooon** [DeadlyMC/QuickCarpet114#60]
`OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[23:55:31] [main/INFO]: Loading for game Minecraft 1.16.2
[23:55:32] [main/INFO]: [FabricLoader] Loading 42 mods: minecraft@1.16.2, fabric-screen-handler-api-v1@1.1.0+872498414e, fabric-renderer-api-v1@0.2.13+eae12eb84e, fabric-networking-blockentity-v0@0.2.5+b50ffc7b4e, fabric-keybindings-v0@0.2.0+3fa9f7c54e, fabric-command-api-v1@1.0.8+5ce533984e, fabricloader@0.9.1+build.205, fabric-tool-attribute-api-v1@1.2.2+ccce563e4e, fabric-renderer-indigo@0.3.4+5d32f5834e, fabric-structure-api-v1@1.0.0+516ece7c4e, fabric-containers-v0@0.1.8+045df74f4e, fabric-object-builder-api-v1@1.6.0+e81ec80b4e, fabric-item-api-v1@1.1.0+29679fd64e, fabric-events-interaction-v0@0.4.0+e2e6cdad4e, fabric-crash-report-info-v1@0.1.2+b7f9825d4e, fabric-game-rule-api-v1@1.0.1+91555cd14e, quickcarpet@2.3.0, fabric-api-base@0.1.3+12a8474c4e, fabric-rendering-v0@1.1.0+534104904e, fabric-rendering-v1@1.2.0+fc24ff244e, fabric-key-binding-api-v1@1.0.1+730711c64e, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d4e, fabric-resource-loader-v0@0.2.9+e5d3217f4e, malilib@0.10.0-dev.21+arne.1, fabric-textures-v0@1.0.4+eae12eb84e, fabric-content-registries-v0@0.1.9+059ea8664e, fabric-tag-extensions-v0@1.0.3+ac8e8c594e, fabric-rendering-fluids-v1@0.1.10+e5d3217f4e, fabric-registry-sync-v0@0.4.3+e5d3217f4e, fabric-commands-v0@0.2.0+52d308364e, fabric-blockrenderlayer-v1@1.1.4+c6a8ea894e, fabric-lifecycle-events-v1@1.2.0+74cc3b204e, fabric-mining-levels-v0@0.1.2+b764ce994e, fabric-renderer-registries-v1@2.1.0+e2862de64e, fabric-events-lifecycle-v0@0.2.0+16acbe5b4e, fabric-loot-tables-v1@1.0.0+fac8f3664e, fabric@0.19.0+build.398-1.16, fabric-particles-v1@0.2.1+0a6f2a704e, fabric-item-groups-v0@0.2.0+438f96364e, fabric-models-v0@0.1.0+dfdb52d64e, fabric-object-builders-v0@0.6.1+ba4afa574e, fabric-networking-v0@0.1.10+e00ecb5f4e
[23:55:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.1 Source=file:/home/minecraft/Skyblock/skyblock.jar Service=Knot/Fabric Env=SERVER
[23:55:36] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[23:55:36] [main/FATAL]: Failed to start the minecraft server
net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'quickcarpet'
        at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193) ~[skyblock.jar:?]
        at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:251) ~[skyblock.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44) ~[skyblock.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[skyblock.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[skyblock.jar:?]
        at net.minecraft.server.Main.main(Main.java:126) [intermediary-server.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [skyblock.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [skyblock.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [skyblock.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [skyblock.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [skyblock.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [skyblock.jar:?]
Caused by: java.lang.RuntimeException: Cannot load class quickcarpet.QuickCarpetClient in environment type SERVER
        at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:76) ~[skyblock.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:185) ~[skyblock.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:152) ~[skyblock.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) ~[skyblock.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredFields(Class.java:3061) ~[?:?]
        at java.lang.Class.getDeclaredField(Class.java:2409) ~[?:?]
        at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:73) ~[skyblock.jar:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) ~[skyblock.jar:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) ~[skyblock.jar:?]
        at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) ~[skyblock.jar:?]`

Make note that my fabric launcher jar file is called skyblock.jar The only mods in the mods folder are Fabric API and Malilib

**Comment by Huntooon** [comment]
Here is the log from just quick carpet

`OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[23:59:55] [main/INFO]: Loading for game Minecraft 1.16.2
[23:59:56] [main/WARN]: Warnings were found! 
 - Mod quickcarpet recommends mod {malilib @ [0.10.0-dev.21+arne.1]}, which is missing!
[23:59:56] [main/INFO]: [FabricLoader] Loading 4 mods: minecraft@1.16.2, fabric-resource-loader-v0@0.2.9+e5d3217f4e, fabricloader@0.9.1+build.205, quickcarpet@2.3.0
[23:59:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.1 Source=file:/home/minecraft/Skyblock/skyblock.jar Service=Knot/Fabric Env=SERVER
[23:59:56] [main/WARN]: Error loading class: net/fabricmc/fabric/impl/registry/sync/RegistrySyncManager (java.lang.ClassNotFoundException: net/fabricmc/fabric/impl/registry/sync/RegistrySyncManager)
[23:59:56] [main/WARN]: @Mixin target net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager was not found quickcarpet.mixins.json:fabricApi.RegistrySyncManagerMixin
[00:00:00] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[00:00:00] [main/FATAL]: Failed to start the minecraft server
net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'quickcarpet'
        at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193) ~[skyblock.jar:?]
        at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:251) ~[skyblock.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44) ~[skyblock.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[skyblock.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[skyblock.jar:?]
        at net.minecraft.server.Main.main(Main.java:126) [intermediary-server.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [skyblock.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [skyblock.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [skyblock.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [skyblock.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [skyblock.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [skyblock.jar:?]
Caused by: java.lang.RuntimeException: Cannot load class quickcarpet.QuickCarpetClient in environment type SERVER
        at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:76) ~[skyblock.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:185) ~[skyblock.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:152) ~[skyblock.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) ~[skyblock.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredFields(Class.java:3061) ~[?:?]
        at java.lang.Class.getDeclaredField(Class.java:2409) ~[?:?]
        at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:73) ~[skyblock.jar:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) ~[skyblock.jar:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) ~[skyblock.jar:?]
        at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) ~[skyblock.jar:?]`

**Comment by skyrising** [comment]
Fixed in f2298b2c1e7f42324ecc82ba26bb5653c8a7f9d1
There hasn't been a release since, but you can get the development build from the actions tab (click on build artifacts and use the jar that doesn't end in -dev or -sources)
