### ISSUE TITLE
Crash when starting a server with lithium 1.16.2

### ISSUE THREAD

**Issue by John-Development** [DeadlyMC/QuickCarpet114#63]
This is the error im getting everytime I try to launch the server (also fails in client) with both quickcarpet and lithium in 1.16.2:

```
Mixin apply failed quickcarpet.mixins.json:betterChunkLoading.ChunkTicketManagerMixin -> net.minecraft.class_3204: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("FIELD") on net/minecraft/class_3204::purgeOnAutosave with priority 1000 cannot inject into net/minecraft/class_3204::method_14045()V merged by me.jellysquid.mods.lithium.mixin.alloc.chunk_ticking.ChunkTicketManagerMixin with priority 1000 [PREINJECT Applicator Phase -> quickcarpet.mixins.json:betterChunkLoading.ChunkTicketManagerMixin -> Prepare Injections ->  -> handler$zdo000$purgeOnAutosave(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("FIELD") on net/minecraft/class_3204::purgeOnAutosave with priority 1000 cannot inject into net/minecraft/class_3204::method_14045()V merged by me.jellysquid.mods.lithium.mixin.alloc.chunk_ticking.ChunkTicketManagerMixin with priority 1000 [PREINJECT Applicator Phase -> quickcarpet.mixins.json:betterChunkLoading.ChunkTicketManagerMixin -> Prepare Injections ->  -> handler$zdo000$purgeOnAutosave(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[minecraft_server.Fabric.jar:?]
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[minecraft_server.Fabric.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[minecraft_server.Fabric.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[minecraft_server.Fabric.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[minecraft_server.Fabric.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[minecraft_server.Fabric.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[minecraft_server.Fabric.jar:?]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[minecraft_server.Fabric.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) ~[minecraft_server.Fabric.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[minecraft_server.Fabric.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) ~[minecraft_server.Fabric.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[minecraft_server.Fabric.jar:?]
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[minecraft_server.Fabric.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[minecraft_server.Fabric.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) ~[minecraft_server.Fabric.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
        at net.minecraft.class_5464.<clinit>(class_5464.java:93) ~[intermediary-server.jar:?]
        at net.minecraft.class_5458.method_30571(class_5458.java:46) ~[intermediary-server.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[intermediary-server.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) [?:1.8.0_242]
        at net.minecraft.class_5458.<clinit>(class_5458.java:74) [intermediary-server.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:237) [intermediary-server.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:42) [intermediary-server.jar:?]
        at net.minecraft.server.Main.main(Main.java:88) [intermediary-server.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [minecraft_server.Fabric.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [minecraft_server.Fabric.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [minecraft_server.Fabric.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [minecraft_server.Fabric.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [minecraft_server.Fabric.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [minecraft_server.Fabric.jar:?]
org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [quickcarpet.mixins.json:betterChunkLoading.ChunkTicketManagerMixin] from phase [DEFAULT] in config [quickcarpet.mixins.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at net.minecraft.class_5464.<clinit>(class_5464.java:93)
        at net.minecraft.class_5458.method_30571(class_5458.java:46)
        at net.minecraft.class_5458.method_30566(class_5458.java:75)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at net.minecraft.class_5458.<clinit>(class_5458.java:74)
        at net.minecraft.class_2378.<clinit>(class_2378.java:237)
        at net.minecraft.class_2966.method_12851(class_2966.java:42)
        at net.minecraft.server.Main.main(Main.java:88)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("FIELD") on net/minecraft/class_3204::purgeOnAutosave with priority 1000 cannot inject into net/minecraft/class_3204::method_14045()V merged by me.jellysquid.mods.lithium.mixin.alloc.chunk_ticking.ChunkTicketManagerMixin with priority 1000 [PREINJECT Applicator Phase -> quickcarpet.mixins.json:betterChunkLoading.ChunkTicketManagerMixin -> Prepare Injections ->  -> handler$zdo000$purgeOnAutosave(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
        ... 28 more
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:51)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:107)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:63)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
        ... 2 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
        ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
        ... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at net.minecraft.class_5464.<clinit>(class_5464.java:93)
        at net.minecraft.class_5458.method_30571(class_5458.java:46)
        at net.minecraft.class_5458.method_30566(class_5458.java:75)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at net.minecraft.class_5458.<clinit>(class_5458.java:74)
        at net.minecraft.class_2378.<clinit>(class_2378.java:237)
        at net.minecraft.server.Main.main(Main.java:88)
        ... 14 more

Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [quickcarpet.mixins.json:betterChunkLoading.ChunkTicketManagerMixin] from phase [DEFAULT] in config [quickcarpet.mixins.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
        ... 28 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("FIELD") on net/minecraft/class_3204::purgeOnAutosave with priority 1000 cannot inject into net/minecraft/class_3204::method_14045()V merged by me.jellysquid.mods.lithium.mixin.alloc.chunk_ticking.ChunkTicketManagerMixin with priority 1000 [PREINJECT Applicator Phase -> quickcarpet.mixins.json:betterChunkLoading.ChunkTicketManagerMixin -> Prepare Injections ->  -> handler$zdo000$purgeOnAutosave(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
        ... 28 more
```

**Comment by skyrising** [comment]
This is already fixed in the development version, which you can find at https://github.com/DeadlyMC/QuickCarpet114/actions/runs/241687671. Now that Mumbo linked here it's probably a good idea to make a proper release soon
