### ISSUE TITLE
Can't find Carpet on launch

### ISSUE THREAD

**Issue by avdeel** [DeadlyMC/QuickCarpet114#72]
When I launch with fabric, I get this error. Tried it with adn without Fabric API, also tried it with all mods and Fabric on 1.16.2
(Sorry for bad image, screenshot doesn't work)

![IMG_20201012_140715](https://user-images.githubusercontent.com/72743364/95745370-43acf180-0c95-11eb-95f4-c70e619dc90e.jpg)

**Comment by altrisi** [comment]
You downloaded the SkyBlock version to use with fabric-carpet, and you are using QuickCarpet. Therefore, you need to either download SkyBlock for QuickCarpet instead ([here](https://github.com/skyrising/skyblock/releases/tag/v3.0.0)) or use fabric-carpet instead.

**Comment by avdeel** [comment]
Thank you, the later option worked, altho with SkyBlock and QuickCarpet, the game kept crashing upon world generation... It's okay tho as I can use the fabric-carpet now, thanks again for the help!

**Comment by skyrising** [comment]
Can you share a crash report of the combination of QuickCarpet and SkyBlock?

**Comment by avdeel** [comment]
This is with 1.16.3

The game crashed whilst exception in server tick loop
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1



---- Minecraft Crash Report ----
// My bad.

Time: 2020.10.20. 13:01
Description: Exception in server tick loop

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_3218.<init>(class_3218.java:204)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:407)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:332)
	at net.minecraft.class_1132.method_3823(class_1132.java:68)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at net.minecraft.server.MinecraftServer$$Lambda$4245/1731775680.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method adjustExitPortalLocation(ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in skyblock.mixins.json:EnderDragonFightMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap skyblock-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1496435176 bytes (1427 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Player Count: 0 / 8; []
	Data Packs: vanilla, fabric/quickcarpet (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by skyrising** [comment]
This is using SkyBlock 3.0.0? That only works on 1.16 and 1.16.1.
For 1.16.2+ you should use a 3.1.0-dev version after https://github.com/skyrising/skyblock/commit/673ec1097259b612b8f75df2035f2c51765df805 (for example [this](https://github.com/skyrising/skyblock/actions/runs/269441800))

**Comment by avdeel** [comment]
I thought about that, altho the skyblock release still says "It should work with every 1.16.x versions", and I didn't find any newer releases, so when it crashed I decided to just wait for any new full version. Didn't know there are any dev versions, thanks.

**Comment by skyrising** [comment]
Updated the release notes to make it clear, that 3.0.0 doesn't work with 1.16.2+
