### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by RealityTest** [DeadlyMC/QuickCarpet114#80]
I set up a fabric server, it launches without the quickcarpet114 mod just fine. The following mods are in the mods folder: 

quickcarpet-3.0.0-dev+b927d4c-dev
malilib-fabric-1.16.4-0.10.0-dev.21+arne.1
fabric-api-0.30.0+1.16

```
[18:50:35] [main/INFO]: Loading for game Minecraft 1.16.5
[18:50:35] [main/INFO]: [FabricLoader] Loading 48 mods: fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-screen-handler-api-v1@1.1.1+ca58154a7d, minecraft@1.16.5, fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabric-command-api-v1@1.0.10+ca58154a7d, fabricloader@0.11.1, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.10+ca58154a7d, fabric-object-builder-api-v1@1.9.3+ca58154a7d, fabric-dimensions-v1@2.0.2+ca58154a7d, java@8, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-game-rule-api-v1@1.0.6+ca58154a7d, quickcarpet@3.0.0-dev+b927d4c, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-api-base@0.2.0+daa38b3d7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-resource-loader-v0@0.4.2+ca58154a7d, malilib@0.10.0-dev.21+arne.1, fabric-textures-v0@1.0.6+ca58154a7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.30.0+1.16, fabric-models-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-particles-v1@0.2.4+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:52)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:108)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:64)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62)
        ... 2 more
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod quickcarpet
        at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:443)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27)
        ... 7 more
Caused by: java.lang.RuntimeException: Namespace (named) does not match current runtime namespace (intermediary)
        at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:47)
        at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:441)
        ... 9 more
```

**Comment by skyrising** [comment]
You are using the `-dev` version which is for modders. Use [`quickcarpet-3.0.0-dev+b927d4c.jar`](https://github.com/DeadlyMC/QuickCarpet114/releases/download/v3.0.0-dev-1.16/quickcarpet-3.0.0-dev+b927d4c.jar).
